### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by GildedHonour** [tewen/paya#2]
Is help needed for the project?

**Comment by tewen** [comment]
@GildedHonour always. We want to implement more parts of the API. If you want to make a contribution, feel free to fork the repo and contribute some pieces. I will add an issue roadmap shortly, as well.

Thanks!

**Comment by GildedHonour** [comment]
@tewen please check my email I sent you first, I sent it a few days priour to this post, in November

**Comment by tewen** [comment]
@GildedHonour Searched for your name, never received an email. me@trevorewen.com

Thanks!
